version: 0.2
phases:
  install:
    commands:
      - sudo yum update -y
      - sudo yum install zip -y
      - echo "Installing dependencies..."
  build:
    commands:
      - zip -r deployment_package.zip lambda_function.py
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name cicd-lambda --zip-file fileb://deployment_package.zip
      - echo "DONE!!"
